apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterrole-apply-leaderworkerset.yaml
- clusterrolebinding-apply-leaderworkerset.yaml
- configmap-openshift-lws-operator-apply-leaderworkerset.yaml
- configmap-openshift-lws-operator-approve-leader-worker-set-script.yaml
- job-openshift-lws-operator-apply-leaderworkerset.yaml
- job-openshift-lws-operator-approve-leader-worker-set.yaml
- namespace-openshift-lws-operator.yaml
- operatorgroup-openshift-lws-operator-leader-worker-set.yaml
- role-openshift-lws-operator-approve-leader-worker-set.yaml
- rolebinding-openshift-lws-operator-approve-leader-worker-set.yaml
- serviceaccount-openshift-lws-operator-apply-leaderworkerset.yaml
- serviceaccount-openshift-lws-operator-approve-leader-worker-set.yaml
- subscription-openshift-lws-operator-leader-worker-set.yaml
