# Source: leaderworkerset/charts/install-lws/templates/install-plan-approvals.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: approve-leader-worker-set
  namespace: openshift-lws-operator
  labels:
    app.kubernetes.io/name: install-lws
    app.kubernetes.io/instance: leaderworkerset
    app.kubernetes.io/version: "0.1.0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: approve-leader-worker-set
subjects:
- kind: ServiceAccount
  name: approve-leader-worker-set
  namespace: openshift-lws-operator
