# Source: leaderworkerset/charts/install-lws/templates/install-plan-approvals.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: approve-leader-worker-set
  namespace: openshift-lws-operator
  labels:
    app.kubernetes.io/name: install-lws
    app.kubernetes.io/instance: leaderworkerset
    app.kubernetes.io/version: "0.1.0"
