apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterrole-patch-pipelines-placement.yaml
- clusterrolebinding-patch-pipelines-placement.yaml
- configmap-openshift-gitops-patch-gitops-placement-script.yaml
- configmap-openshift-operators-patch-pipelines-placement-script.yaml
- deployment-rhoai-model-registries-model-registry-minio.yaml
- deployment-rhoai-model-registries-model-registry-mysql.yaml
- job-openshift-gitops-patch-gitops-placement.yaml
- job-openshift-operators-patch-pipelines-placement.yaml
- modelregistry-rhoai-model-registries-rhoai-registry.yaml
- namespace-openshift-gitops-operator.yaml
- namespace-openshift-gitops.yaml
- namespace-openshift-operators.yaml
- namespace-openshift-pipelines.yaml
- namespace-rhoai-model-registries.yaml
- namespace-rhods-notebooks.yaml
- operatorgroup-openshift-gitops-operator-openshift-gitops-operator.yaml
- persistentvolumeclaim-openshift-pipelines-pipelines-artifacts.yaml
- persistentvolumeclaim-rhoai-model-registries-model-registry-minio-data.yaml
- persistentvolumeclaim-rhoai-model-registries-model-registry-mysql-data.yaml
- persistentvolumeclaim-rhods-notebooks-rhods-notebooks-shared.yaml
- role-openshift-gitops-patch-gitops-placement.yaml
- rolebinding-openshift-gitops-patch-gitops-placement.yaml
- secret-rhoai-model-registries-model-registry-minio.yaml
- secret-rhoai-model-registries-model-registry-mysql.yaml
- service-rhoai-model-registries-model-registry-minio.yaml
- service-rhoai-model-registries-model-registry-mysql.yaml
- serviceaccount-openshift-gitops-patch-gitops-placement.yaml
- serviceaccount-openshift-operators-patch-pipelines-placement.yaml
- subscription-openshift-gitops-operator-openshift-gitops-operator.yaml
- subscription-openshift-operators-openshift-pipelines-operator-rh.yaml
