# Source: platform-addons/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rhods-notebooks-shared
  namespace: rhods-notebooks
  labels:
    app.kubernetes.io/name: platform-addons
    app.kubernetes.io/instance: platform-addons
    platform-addons.rhoai.io/pvc: notebooksShared
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-csi
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
