# Source: platform-addons/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipelines-artifacts
  namespace: openshift-pipelines
  labels:
    app.kubernetes.io/name: platform-addons
    app.kubernetes.io/instance: platform-addons
    platform-addons.rhoai.io/pvc: pipelinesArtifacts
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-csi
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
