# Source: platform-addons/templates/job-patch-gitops.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: patch-gitops-placement
  namespace: openshift-gitops
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["argocds"]
    verbs: ["get", "list", "patch", "update"]
