# Source: platform-addons/templates/minio.yaml
apiVersion: v1
kind: Secret
metadata:
  name: model-registry-minio
  namespace: rhoai-model-registries
  labels:
    app.kubernetes.io/name: platform-addons
    app.kubernetes.io/instance: platform-addons
    opendatahub.io/dashboard: "true"
    opendatahub.io/managed: "true"
  annotations:
    opendatahub.io/connection-type: s3
    opendatahub.io/connection-type-ref: s3
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "minio"
  AWS_SECRET_ACCESS_KEY: "opentlc-lab"
  AWS_S3_ENDPOINT: http://model-registry-minio.rhoai-model-registries.svc.cluster.local:9000
  AWS_S3_BUCKET: models
  AWS_DEFAULT_REGION: us-east-1
