# Source: platform-addons/templates/mysql.yaml
apiVersion: v1
kind: Secret
metadata:
  name: model-registry-mysql
  namespace: rhoai-model-registries
  labels:
    app.kubernetes.io/name: platform-addons
    app.kubernetes.io/instance: platform-addons
type: Opaque
stringData:
  database-name: "modelregistry"
  database-user: "mlmduser"
  database-password: "opentlc-lab"
  database-root-password: "opentlc-lab"
