apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap-models-as-a-service-patch-tenant-telemetry-script.yaml
- job-models-as-a-service-patch-tenant-telemetry.yaml
- maasauthpolicy-models-as-a-service-free-models-access.yaml
- maasauthpolicy-models-as-a-service-premium-models-access.yaml
- maasmodelref-ai-models-deepseek-coder-33b.yaml
- maasmodelref-ai-models-granite-3-0-8b-instruct.yaml
- maasmodelref-ai-models-qwen25-coder-32b.yaml
- maassubscription-models-as-a-service-free-models-subscription.yaml
- maassubscription-models-as-a-service-premium-models-subscription.yaml
- role-models-as-a-service-patch-tenant-telemetry.yaml
- rolebinding-models-as-a-service-patch-tenant-telemetry.yaml
- serviceaccount-models-as-a-service-patch-tenant-telemetry.yaml
