# Source: maas-postgres/templates/postgres.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
  namespace: redhat-ods-applications
  labels:
    app: postgres
    purpose: poc
stringData:
  POSTGRES_USER: "maas"
  POSTGRES_PASSWORD: "opentlc-lab"
  POSTGRES_DB: "maas"
