# Source: maas-postgres/templates/job-maas-db-config.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-maas-db-config
  namespace: redhat-ods-applications
  labels:
    app.kubernetes.io/name: maas-postgres
    app.kubernetes.io/instance: maas-postgres
