# Source: platform-addons/templates/namespaces.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-gitops
  labels:
    app.kubernetes.io/name: platform-addons
    app.kubernetes.io/instance: platform-addons
