# Source: platform-addons/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-registry-minio-data
  namespace: rhoai-model-registries
  labels:
    app.kubernetes.io/name: platform-addons
    app.kubernetes.io/instance: platform-addons
    platform-addons.rhoai.io/pvc: modelRegistryMinio
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nutanix-files-dynamic
  resources:
    requests:
      storage: 200Gi
  volumeMode: Filesystem
