apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- certmanager-cluster.yaml
- configmap-cert-manager-operator-approve-openshift-cert-manager-operator-script.yaml
- job-cert-manager-operator-approve-openshift-cert-manager-operator.yaml
- namespace-cert-manager-operator.yaml
- operatorgroup-cert-manager-operator-openshift-cert-manager-operator.yaml
- role-cert-manager-operator-approve-openshift-cert-manager-operator.yaml
- rolebinding-cert-manager-operator-approve-openshift-cert-manager-operator.yaml
- serviceaccount-cert-manager-operator-approve-openshift-cert-manager-operator.yaml
- subscription-cert-manager-operator-openshift-cert-manager-operator.yaml
