apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap-openshift-ingress-maas-gateway-options.yaml
- gateway-openshift-ingress-maas-default-gateway.yaml
- gatewayclass-openshift-default.yaml
- route-openshift-ingress-maas-default-gateway.yaml
