apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - appproject.yaml
  - cert-manager.yaml
  - observability-operators.yaml
  - platform-addons.yaml
  - nvidia-gpu-enablement.yaml
  - leaderworkerset.yaml
  - rhcl.yaml
  - gateway-api.yaml
  - maas-postgres.yaml
  - openshift-ai.yaml
  - model-registry-cr.yaml
  - llmisvc-granite-8b.yaml
  - llmisvc-qwen25-coder-32b.yaml
  - llmisvc-deepseek-coder-33b.yaml
  - maas-subscriptions.yaml
