# Source: llmisvc/templates/llminferenceservice.yaml
apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    openshift.io/display-name: Granite 3.0 8B Instruct
    opendatahub.io/model-type: "generative"
    opendatahub.io/genai-use-case: "chat"
    openshift.io/description: "IBM Granite 3.0 8B Instruct for general chat and instruction following."
    opendatahub.io/hardware-profile-name: gpu
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
  labels:
    app.kubernetes.io/name: granite-3-0-8b-instruct
    app.kubernetes.io/instance: llmisvc-granite-8b
    app.kubernetes.io/version: "3.3.1"
    opendatahub.io/dashboard: "true"
    opendatahub.io/genai-asset: "true"
  name: granite-3-0-8b-instruct
spec:
  model:
    name: granite-3-0-8b-instruct
    uri: hf://ibm-granite/granite-3.0-8b-instruct
  replicas: 2
  router:
    gateway:
      refs:
        - name: maas-default-gateway
          namespace: openshift-ingress
    route: {}
    scheduler: {}
  template:
    containers:
      - name: main
        image: registry.redhat.io/rhaiis/vllm-cuda-rhel9:3.3.1
        env:
          - name: VLLM_ADDITIONAL_ARGS
            value: >-
              --max-model-len=4096 --tensor-parallel-size=1 --pipeline-parallel-size=1 --trust-remote-code
        envFrom:
            - secretRef:
                name: hf-token
        resources:
          limits:
            cpu: "4"
            memory: 32Gi
            nvidia.com/gpu: "1"
          requests:
            cpu: "2"
            memory: 16Gi
            nvidia.com/gpu: "1"
    nodeSelector:
      nvidia.com/gpu.present: "true"
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: granite-3-0-8b-instruct
            topologyKey: kubernetes.io/hostname
          weight: 100
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
