# Source: openshift-ai/templates/job-patch-segment-key-config.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: patch-segment-key-config
  namespace: redhat-ods-applications
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
