# Source: openshift-ai/templates/job-patch-controller-resources.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: patch-controller-resources
  namespace: redhat-ods-applications
  labels:
    app.kubernetes.io/name: openshift-ai
    app.kubernetes.io/instance: openshift-ai
    app.kubernetes.io/version: "0.1.0"
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
