apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterrolebinding-rhcl-enable-console-plugin.yaml
- configmap-kuadrant-system-apply-kuadrant.yaml
- configmap-kuadrant-system-approve-rhcl-operator-script.yaml
- configmap-kuadrant-system-restart-kuadrant-operator-script.yaml
- configmap-kuadrant-system-rhcl-bootstrap-scripts.yaml
- job-kuadrant-system-apply-kuadrant.yaml
- job-kuadrant-system-approve-rhcl-operator.yaml
- job-kuadrant-system-enable-console-plugin.yaml
- job-kuadrant-system-patch-authorino-ca.yaml
- job-kuadrant-system-patch-authorino-service.yaml
- job-kuadrant-system-patch-authorino-tls.yaml
- job-kuadrant-system-patch-kuadrant-operator-resources.yaml
- job-kuadrant-system-patch-rhcl-csv.yaml
- job-kuadrant-system-restart-kuadrant-operator.yaml
- namespace-kuadrant-system.yaml
- operatorgroup-kuadrant-system-rhcl-operator.yaml
- role-kuadrant-system-apply-kuadrant.yaml
- role-kuadrant-system-approve-rhcl-operator.yaml
- role-kuadrant-system-patch-authorino-ca.yaml
- role-kuadrant-system-patch-authorino-service.yaml
- role-kuadrant-system-patch-authorino-tls.yaml
- role-kuadrant-system-patch-kuadrant-operator-resources.yaml
- role-kuadrant-system-patch-rhcl-csv.yaml
- role-kuadrant-system-restart-kuadrant-operator.yaml
- rolebinding-kuadrant-system-apply-kuadrant.yaml
- rolebinding-kuadrant-system-approve-rhcl-operator.yaml
- rolebinding-kuadrant-system-patch-authorino-ca.yaml
- rolebinding-kuadrant-system-patch-authorino-service.yaml
- rolebinding-kuadrant-system-patch-authorino-tls.yaml
- rolebinding-kuadrant-system-patch-kuadrant-operator-resources.yaml
- rolebinding-kuadrant-system-patch-rhcl-csv.yaml
- rolebinding-kuadrant-system-restart-kuadrant-operator.yaml
- serviceaccount-kuadrant-system-apply-kuadrant.yaml
- serviceaccount-kuadrant-system-approve-rhcl-operator.yaml
- serviceaccount-kuadrant-system-enable-console-plugin.yaml
- serviceaccount-kuadrant-system-patch-authorino-ca.yaml
- serviceaccount-kuadrant-system-patch-authorino-service.yaml
- serviceaccount-kuadrant-system-patch-authorino-tls.yaml
- serviceaccount-kuadrant-system-patch-kuadrant-operator-resources.yaml
- serviceaccount-kuadrant-system-patch-rhcl-csv.yaml
- serviceaccount-kuadrant-system-restart-kuadrant-operator.yaml
- subscription-kuadrant-system-rhcl-operator.yaml
