# Source: rhcl/templates/job-apply-kuadrant.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: apply-kuadrant
  namespace: kuadrant-system
  labels:
    app.kubernetes.io/name: rhcl
    app.kubernetes.io/instance: rhcl
    app.kubernetes.io/version: "0.1.0"
rules:
  - apiGroups: ["kuadrant.io"]
    resources: ["kuadrants"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
