# Source: rhcl/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restart-kuadrant-operator
  namespace: kuadrant-system
  labels:
    app.kubernetes.io/name: rhcl
    app.kubernetes.io/instance: rhcl
    app.kubernetes.io/version: "0.1.0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: restart-kuadrant-operator
subjects:
  - kind: ServiceAccount
    name: restart-kuadrant-operator
    namespace: kuadrant-system
