# Source: rhcl/templates/job-apply-kuadrant.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apply-kuadrant
  namespace: kuadrant-system
  labels:
    app.kubernetes.io/name: rhcl
    app.kubernetes.io/instance: rhcl
    app.kubernetes.io/version: "0.1.0"
