# Source: openshift-ai/templates/job-apply-dsc.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apply-dsc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apply-dsc
subjects:
  - kind: ServiceAccount
    name: apply-dsc
    namespace: redhat-ods-applications
