# Source: openshift-ai/charts/install-rhoai/templates/install-plan-approvals.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: approve-rhods-operator
  namespace: redhat-ods-operator
  labels:
    app.kubernetes.io/name: install-rhoai
    app.kubernetes.io/instance: openshift-ai
    app.kubernetes.io/version: "0.1.0"
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 270
  template:
    spec:
      serviceAccountName: approve-rhods-operator
      restartPolicy: Never
      containers:
      - name: approve-operator
        image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
        imagePullPolicy: IfNotPresent
        command: ["/mnt/approve-operator.sh"]
        volumeMounts:
          - name: approve-operator-script
            mountPath: /mnt
      volumes:
        - name: approve-operator-script
          configMap:
            name: approve-rhods-operator-script
            defaultMode: 493
