apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterrole-apply-dsc.yaml
- clusterrole-apply-dsci.yaml
- clusterrolebinding-apply-dsc.yaml
- clusterrolebinding-apply-dsci.yaml
- configmap-openshift-monitoring-cluster-monitoring-config.yaml
- configmap-redhat-ods-applications-apply-dsc.yaml
- configmap-redhat-ods-applications-apply-hardwareprofiles.yaml
- configmap-redhat-ods-applications-apply-odh-dashboard-config.yaml
- configmap-redhat-ods-applications-notebook-controller-culler-config.yaml
- configmap-redhat-ods-applications-patch-controller-resources-script.yaml
- configmap-redhat-ods-applications-patch-segment-key-config-script.yaml
- configmap-redhat-ods-applications-restart-rhods-dashboard-script.yaml
- configmap-redhat-ods-operator-apply-dsci.yaml
- configmap-redhat-ods-operator-approve-rhods-operator-script.yaml
- job-redhat-ods-applications-apply-dsc.yaml
- job-redhat-ods-applications-apply-hardwareprofiles.yaml
- job-redhat-ods-applications-apply-odh-dashboard-config.yaml
- job-redhat-ods-applications-patch-controller-resources-data-science-collector.yaml
- job-redhat-ods-applications-patch-controller-resources-kserve-controller.yaml
- job-redhat-ods-applications-patch-controller-resources-llmisvc-controller.yaml
- job-redhat-ods-applications-patch-controller-resources-maas-controller.yaml
- job-redhat-ods-applications-patch-segment-key-config.yaml
- job-redhat-ods-applications-restart-rhods-dashboard.yaml
- job-redhat-ods-operator-apply-dsci.yaml
- job-redhat-ods-operator-approve-rhods-operator.yaml
- namespace-redhat-ods-monitoring.yaml
- namespace-redhat-ods-operator.yaml
- operatorgroup-redhat-ods-operator-rhods-operator.yaml
- role-redhat-ods-applications-apply-hardwareprofiles.yaml
- role-redhat-ods-applications-apply-odh-dashboard-config.yaml
- role-redhat-ods-applications-patch-controller-resources-deployments.yaml
- role-redhat-ods-applications-patch-segment-key-config.yaml
- role-redhat-ods-applications-restart-rhods-dashboard.yaml
- role-redhat-ods-monitoring-patch-controller-resources-monitoring.yaml
- role-redhat-ods-operator-approve-rhods-operator.yaml
- rolebinding-redhat-ods-applications-apply-hardwareprofiles.yaml
- rolebinding-redhat-ods-applications-apply-odh-dashboard-config.yaml
- rolebinding-redhat-ods-applications-patch-controller-resources-deployments.yaml
- rolebinding-redhat-ods-applications-patch-segment-key-config.yaml
- rolebinding-redhat-ods-applications-restart-rhods-dashboard.yaml
- rolebinding-redhat-ods-applications-user-hardwareprofile-view.yaml
- rolebinding-redhat-ods-monitoring-patch-controller-resources-monitoring.yaml
- rolebinding-redhat-ods-operator-approve-rhods-operator.yaml
- serviceaccount-redhat-ods-applications-apply-dsc.yaml
- serviceaccount-redhat-ods-applications-apply-hardwareprofiles.yaml
- serviceaccount-redhat-ods-applications-apply-odh-dashboard-config.yaml
- serviceaccount-redhat-ods-applications-patch-controller-resources.yaml
- serviceaccount-redhat-ods-applications-patch-segment-key-config.yaml
- serviceaccount-redhat-ods-applications-restart-rhods-dashboard.yaml
- serviceaccount-redhat-ods-operator-apply-dsci.yaml
- serviceaccount-redhat-ods-operator-approve-rhods-operator.yaml
- subscription-redhat-ods-operator-rhods-operator.yaml
- telemetry-openshift-ingress-latency-per-subscription.yaml
- telemetrypolicy-openshift-ingress-maas-telemetry.yaml
