# Source: openshift-ai/charts/install-rhoai/templates/operatorgroups.yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhods-operator
  namespace: redhat-ods-operator
  labels:
    app.kubernetes.io/name: install-rhoai
    app.kubernetes.io/instance: openshift-ai
    app.kubernetes.io/version: "0.1.0"
spec:
  upgradeStrategy: Default
