apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterrole-apply-gpu-cluster-policy.yaml
- clusterrolebinding-apply-gpu-cluster-policy.yaml
- configmap-nvidia-gpu-operator-apply-gpu-cluster-policy.yaml
- configmap-nvidia-gpu-operator-approve-gpu-operator-certified-script.yaml
- configmap-openshift-config-managed-nvidia-dcgm-exporter-dashboard.yaml
- configmap-openshift-nfd-apply-nfd-instance.yaml
- configmap-openshift-nfd-approve-nfd-script.yaml
- job-nvidia-gpu-operator-apply-gpu-cluster-policy.yaml
- job-nvidia-gpu-operator-approve-gpu-operator-certified.yaml
- job-openshift-nfd-apply-nfd-instance.yaml
- job-openshift-nfd-approve-nfd.yaml
- namespace-nvidia-gpu-operator.yaml
- namespace-openshift-nfd.yaml
- operatorgroup-nvidia-gpu-operator-nvidia-gpu-operator.yaml
- operatorgroup-openshift-nfd-openshift-nfd.yaml
- role-nvidia-gpu-operator-approve-gpu-operator-certified.yaml
- role-openshift-nfd-apply-nfd-instance.yaml
- role-openshift-nfd-approve-nfd.yaml
- rolebinding-nvidia-gpu-operator-approve-gpu-operator-certified.yaml
- rolebinding-openshift-nfd-apply-nfd-instance.yaml
- rolebinding-openshift-nfd-approve-nfd.yaml
- serviceaccount-nvidia-gpu-operator-apply-gpu-cluster-policy.yaml
- serviceaccount-nvidia-gpu-operator-approve-gpu-operator-certified.yaml
- serviceaccount-openshift-nfd-apply-nfd-instance.yaml
- serviceaccount-openshift-nfd-approve-nfd.yaml
- subscription-nvidia-gpu-operator-gpu-operator-certified.yaml
- subscription-openshift-nfd-nfd.yaml
