# Source: nvidia-gpu-enablement/templates/nfd/job-apply-nodefeaturediscovery.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: apply-nfd-instance
  namespace: openshift-nfd
rules:
  - apiGroups: ["nfd.openshift.io"]
    resources: ["nodefeaturediscoveries"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
