# Source: nvidia-gpu-enablement/charts/install-nvidia-operators/templates/install-plan-approvals.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: approve-nfd
  namespace: openshift-nfd
  labels:
    app.kubernetes.io/name: install-nvidia-operators
    app.kubernetes.io/instance: nvidia-gpu-enablement
    app.kubernetes.io/version: "0.1.0"
rules:
  - apiGroups:
      - operators.coreos.com
    resources:
      - installplans
    verbs:
      - get
      - list
      - patch
      - update
