# Source: nvidia-gpu-enablement/charts/install-nvidia-operators/templates/install-plan-approvals.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: approve-gpu-operator-certified
  namespace: nvidia-gpu-operator
  labels:
    app.kubernetes.io/name: install-nvidia-operators
    app.kubernetes.io/instance: nvidia-gpu-enablement
    app.kubernetes.io/version: "0.1.0"
