# Source: nvidia-gpu-enablement/templates/nvidia-gpu-operator/job-apply-clusterpolicy.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apply-gpu-cluster-policy
  namespace: nvidia-gpu-operator
