apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: rhoai
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: OpenShift AI 3.4 + MaaS (apps-of-apps)
  sourceRepos:
    - https://github.com/abelluque/rhoai-gitops.git
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
