apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - appproject.yaml
  - gitops-controller-rbac.yaml
  - cert-manager.yaml
  - observability-operators.yaml
  - platform-addons.yaml
  - leaderworkerset.yaml
  - rhcl.yaml
  - gateway-api.yaml
  - maas-postgres.yaml
  - openshift-ai.yaml
  - model-registry-cr.yaml
  - llmisvc-granite.yaml
  - maas-subscriptions.yaml
