apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maas-subscriptions
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: rhoai-maas
    rhoai.example.com/cluster: opentlc
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: rhoai
  source:
    repoURL: https://github.com/abelluque/rhoai-gitops.git
    targetRevision: rhoai-maas-demo-platform
    path: components/maas-subscriptions/overlays/opentlc
  destination:
    server: https://kubernetes.default.svc
    namespace: models-as-a-service
  ignoreDifferences:
    - group: operators.coreos.com
      kind: Subscription
      jsonPointers:
        - /spec/startingCSV
        - /status
    - group: operators.coreos.com
      kind: InstallPlan
      jsonPointers:
        - /spec/approved
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 20
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
