# Source: rhcl/templates/job-patch-authorino-ca.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: patch-authorino-ca
  namespace: kuadrant-system
  labels:
    app.kubernetes.io/name: rhcl
    app.kubernetes.io/instance: rhcl
    app.kubernetes.io/version: "0.1.0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: patch-authorino-ca
subjects:
  - kind: ServiceAccount
    name: patch-authorino-ca
    namespace: kuadrant-system
