# Source: rhcl/templates/job-patch-authorino-tls.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: patch-authorino-tls
  namespace: kuadrant-system
  labels:
    app.kubernetes.io/name: rhcl
    app.kubernetes.io/instance: rhcl
    app.kubernetes.io/version: "0.1.0"
