# Source: rhcl/templates/job-patch-rhcl-csv.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: patch-rhcl-csv
  namespace: kuadrant-system
  labels:
    app.kubernetes.io/name: rhcl
    app.kubernetes.io/instance: rhcl
    app.kubernetes.io/version: "0.1.0"
