# Source: rhcl/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: restart-kuadrant-operator
  namespace: kuadrant-system
  labels:
    app.kubernetes.io/name: rhcl
    app.kubernetes.io/instance: rhcl
    app.kubernetes.io/version: "0.1.0"
