# Source: maas-postgres/templates/job-label-gateway-access.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: maas-postgres-label-gateway-access
  labels:
    app.kubernetes.io/name: maas-postgres
    app.kubernetes.io/instance: maas-postgres
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch", "patch", "update"]
