apiVersion: v1
kind: Namespace
metadata:
  name: redhat-ods-applications
  labels:
    app.kubernetes.io/name: maas-postgres
    app.kubernetes.io/instance: maas-postgres
    app.kubernetes.io/part-of: rhoai-maas
    maas.opendatahub.io/gateway-access: "true"
