# Source: maas-postgres/templates/job-label-gateway-access.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: label-gateway-access
  namespace: redhat-ods-applications
  labels:
    app.kubernetes.io/name: maas-postgres
    app.kubernetes.io/instance: maas-postgres
